config/routes.rb
Rails.application.routes.draw do
  root to:  'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @books = Book.all

  end
  def top
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
     @books = Book.all
      render :index
    end
  end
  def index
    @books = Book.all
    @book = Book.new

  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
  if @book.save
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
  else
     @books = Book.all
      render :edit
  end

  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def back
    book = Book.find(params[:id])
    book.back
    redirect_to '/books'
  end

  def start
    book = Book.find(params[:id])
    redirect_to '/books'
  end
 private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, local: true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <p><%= f.submit 'Update Book' %></p>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to 'Back', books_path %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>






<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
       <td> <%= book.title %></td>
      <td> <%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>

<% end %>
  </tbody>
</table>
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div>
 <%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
  <p> <%= f.text_field :title %></p>

  <h4>Body</h4>
  <p><%= f.text_area :body %></p>

  <p><%= f.submit 'Create Book' %></p>

 <% end %>
</div>

app/views/books/show.html.erb
<div>
    <%= flash[:notice] %>
</div>





<h2>Title:</h2>
<p><%= @book.title %></p>

<h2>Body:</h2>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<h1>ようこそ　Bookersへ！</h1>
<p>
  Bookersでは、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し交換することができます
</p>
<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>